### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by maciekstosio** [mwittig/node-fronius-solar#8]
Hi,
when I run example i'm getting request timeouts. When I'm trying curl sometimes I'm getting 404. I provided device ID, checking your code I assume that port doesn't matter and I provided found in settings. Any Idea what I'm doing wrong?

**Comment by mwittig** [comment]
Hi, the port is 80 (default port for HTTP). Which type of Fronius device/gateway do you have and which service function(s) are you trying to call? Note, there are different versions of the Fronius API and service endpoints provided depend on the API version.

**Comment by maciekstosio** [comment]
Well the problem was just IP and I found the right one. Sorry for trouble and thank you for so quick answer.
The things I found out are:
- As far as I understand you never use port in your lib so maybe there is no point in providing it (in example)
- deviceId is misleading, because there is something like deviceId for inverter but where it comes to API it's just index as far as I understand

**Comment by mwittig** [comment]
Well, the port is applied, but generally it is not required. It is mainly required for testing purposes or case where the device is accessed via an intermediate with port mapping (NAT router, firewall, or VPN gateway, for example). I'll clarify this by setting up documentation. Regarding deviceId it really depends on the type of API used. Agin, a matter of documentation
